environment:
  EAFILE: src/EA31337.mq4
init:
- ps: Set-ExecutionPolicy "RemoteSigned" -Scope Process -Confirm:$false
- ps: Set-ExecutionPolicy "RemoteSigned" -Scope CurrentUser -Confirm:$false
- ps: Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine
- ps: scoop
- ps: if (Get-Command scoop  -errorAction SilentlyContinue) { echo "Scoop already installed, skipping." } else { iex (new-object net.webclient).downloadstring('https://get.scoop.sh') }
install:
- appveyor DownloadFile https://github.com/EA31337/MetaEditor/raw/master/metaeditor64.exe
- scoop install ruby python
- ps: scoop install shellcheck
before_test:
- git submodule update --init
- shellcheck --version
#- echo ^#define %MODE% >> src/include/EA31337/ea-mode.mqh
test_script:
- ps: Get-ChildItem -File scripts | Foreach {shellcheck $_.fullname}
- metaeditor64 /mql4 /s /compile:.. /inc:.. /log:mql4.log || exit /b 0
- metaeditor64 /mql5 /s /compile:.. /inc:.. /log:mql5.log || exit /b 0
- type mql4.log mql5.log
- ruby -e "if File.open('mql4.log', mode:'rb:BOM|UTF-16LE').readlines.grep(Regexp.new '[1-9] error'.encode(Encoding::UTF_16LE)) {exit 1}; end"
- ruby -e "if File.open('mql4.log', mode:'rb:BOM|UTF-16LE').readlines.grep(Regexp.new '[1-9] warning'.encode(Encoding::UTF_16LE)) {exit 1}; end"
- ruby -e "if File.open('mql4.log', mode:'rb:BOM|UTF-16LE').readlines.grep(Regexp.new '[1-9][0-9] error'.encode(Encoding::UTF_16LE)) {exit 1}; end"
- ruby -e "if File.open('mql4.log', mode:'rb:BOM|UTF-16LE').readlines.grep(Regexp.new '[1-9][0-9] warning'.encode(Encoding::UTF_16LE)) {exit 1}; end"
- ruby -e "if File.open('mql5.log', mode:'rb:BOM|UTF-16LE').readlines.grep(Regexp.new '[1-9] error'.encode(Encoding::UTF_16LE)) {exit 1}; end"
- ruby -e "if File.open('mql5.log', mode:'rb:BOM|UTF-16LE').readlines.grep(Regexp.new '[1-9] warning'.encode(Encoding::UTF_16LE)) {exit 1}; end"
- ruby -e "if File.open('mql5.log', mode:'rb:BOM|UTF-16LE').readlines.grep(Regexp.new '[1-9][0-9] error'.encode(Encoding::UTF_16LE)) {exit 1}; end"
- ruby -e "if File.open('mql5.log', mode:'rb:BOM|UTF-16LE').readlines.grep(Regexp.new '[1-9][0-9] warning'.encode(Encoding::UTF_16LE)) {exit 1}; end"
build: off
platform: x86
